// frontend/src/components/OnboardingForm.tsx
import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from 'yup';
import {
  Box,
  Paper,
  TextField,
  Button,
  Stepper,
  Step,
  StepLabel,
  Typography,
  MenuItem,
  LinearProgress,
  Alert,
} from '@mui/material';
import { useNavigate } from 'react-router-dom';
import apiClient from '../api/client';
import { OnboardingRequest } from '../types';

const schema = yup.object({
  tradingName: yup.string().required('Trading name is required'),
  contactName: yup.string().required('Contact name is required'),
  contactEmail: yup.string().email('Valid email is required').required('Email is required'),
  contactPhone: yup.string(),
  companyAddress: yup.string(),
  industry: yup.string(),
  companySize: yup.string(),
  requestType: yup.string(),
  region: yup.string(),
  notes: yup.string(),
});

type FormData = yup.InferType<typeof schema>;

const steps = ['Company Information', 'Business Details', 'Additional Information'];

const OnboardingForm: React.FC = () => {
  const [activeStep, setActiveStep] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<OnboardingRequest | null>(null);
  const navigate = useNavigate();

  const {
    register,
    handleSubmit,
    formState: { errors },
    watch,
  } = useForm<FormData>({
    resolver: yupResolver(schema),
  });

  const requestType = watch('requestType');

  const onSubmit = async (data: FormData) => {
    setLoading(true);
    setError(null);

    try {
      const response = await apiClient.post<{ success: boolean; data: OnboardingRequest }>('/onboarding', data);
      
      if (response.data.success) {
        setSuccess(response.data.data);
        setTimeout(() => {
          navigate(`/request/${response.data.data.id}`);
        }, 2000);
      }
    } catch (err: any) {
      setError(err.response?.data?.error || 'Failed to submit request');
    } finally {
      setLoading(false);
    }
  };

  const handleNext = () => {
    setActiveStep((prev) => prev + 1);
  };

  const handleBack = () => {
    setActiveStep((prev) => prev - 1);
  };

  if (success) {
    return (
      <Paper sx={{ p: 4, textAlign: 'center' }}>
        <Alert severity="success" sx={{ mb: 2 }}>
          Request submitted successfully!
        </Alert>
        <Typography variant="h5" gutterBottom>
          Reference Number: {success.referenceNumber}
        </Typography>
        <Typography variant="body1" color="text.secondary">
          Redirecting to request details...
        </Typography>
      </Paper>
    );
  }

  return (
    <Paper sx={{ p: 4 }}>
      <Typography variant="h4" gutterBottom>
        New Onboarding Request
      </Typography>
      
      <Stepper activeStep={activeStep} sx={{ mt: 4, mb: 4 }}>
        {steps.map((label) => (
          <Step key={label}>
            <StepLabel>{label}</StepLabel>
          </Step>
        ))}
      </Stepper>

      <LinearProgress variant="determinate" value={((activeStep + 1) / steps.length) * 100} sx={{ mb: 4 }} />

      {error && (
        <Alert severity="error" sx={{ mb: 2 }}>
          {error}
        </Alert>
      )}

      <form onSubmit={handleSubmit(onSubmit)}>
        {activeStep === 0 && (
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
            <TextField
              label="Trading Name"
              {...register('tradingName')}
              error={!!errors.tradingName}
              helperText={errors.tradingName?.message}
              fullWidth
              required
            />
            <TextField
              label="Contact Name"
              {...register('contactName')}
              error={!!errors.contactName}
              helperText={errors.contactName?.message}
              fullWidth
              required
            />
            <TextField
              label="Contact Email"
              type="email"
              {...register('contactEmail')}
              error={!!errors.contactEmail}
              helperText={errors.contactEmail?.message}
              fullWidth
              required
            />
            <TextField
              label="Contact Phone"
              {...register('contactPhone')}
              error={!!errors.contactPhone}
              helperText={errors.contactPhone?.message}
              fullWidth
            />
            <TextField
              label="Company Address"
              {...register('companyAddress')}
              multiline
              rows={3}
              fullWidth
            />
          </Box>
        )}

        {activeStep === 1 && (
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
            <TextField
              label="Industry"
              select
              {...register('industry')}
              fullWidth
            >
              <MenuItem value="Manufacturing">Manufacturing</MenuItem>
              <MenuItem value="Retail">Retail</MenuItem>
              <MenuItem value="Logistics">Logistics</MenuItem>
              <MenuItem value="Other">Other</MenuItem>
            </TextField>
            <TextField
              label="Company Size"
              select
              {...register('companySize')}
              fullWidth
            >
              <MenuItem value="Small">Small</MenuItem>
              <MenuItem value="Medium">Medium</MenuItem>
              <MenuItem value="Large">Large</MenuItem>
              <MenuItem value="Enterprise">Enterprise</MenuItem>
            </TextField>
            <TextField
              label="Request Type"
              select
              {...register('requestType')}
              fullWidth
            >
              <MenuItem value="New Installation">New Installation</MenuItem>
              <MenuItem value="Upgrade">Upgrade</MenuItem>
              <MenuItem value="Migration">Migration</MenuItem>
            </TextField>
            <TextField
              label="Region"
              select
              {...register('region')}
              fullWidth
            >
              <MenuItem value="North">North</MenuItem>
              <MenuItem value="South">South</MenuItem>
              <MenuItem value="East">East</MenuItem>
              <MenuItem value="West">West</MenuItem>
              <MenuItem value="International">International</MenuItem>
            </TextField>
          </Box>
        )}

        {activeStep === 2 && (
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
            <TextField
              label="Notes"
              {...register('notes')}
              multiline
              rows={4}
              fullWidth
            />
            {requestType === 'Upgrade' && (
              <TextField
                label="Current Version (if applicable)"
                fullWidth
                helperText="Additional field for upgrade requests"
              />
            )}
          </Box>
        )}

        <Box sx={{ display: 'flex', justifyContent: 'space-between', mt: 4 }}>
          <Button
            disabled={activeStep === 0}
            onClick={handleBack}
          >
            Back
          </Button>
          {activeStep < steps.length - 1 ? (
            <Button variant="contained" onClick={handleNext}>
              Next
            </Button>
          ) : (
            <Button
              type="submit"
              variant="contained"
              disabled={loading}
            >
              {loading ? 'Submitting...' : 'Submit'}
            </Button>
          )}
        </Box>
      </form>
    </Paper>
  );
};

export default OnboardingForm;

// frontend-solid/src/components/OnboardingForm.tsx
import { createSignal, Show } from 'solid-js';
import { useNavigate } from '@solidjs/router';
import apiClient from '../api/client';
import type { OnboardingRequest, ApiResponse } from '../types';

interface FormData {
  tradingName: string;
  contactName: string;
  contactEmail: string;
  contactPhone: string;
  companyAddress: string;
  industry: string;
  companySize: string;
  requestType: string;
  region: string;
  notes: string;
}

export default function OnboardingForm() {
  const navigate = useNavigate();
  const [activeStep, setActiveStep] = createSignal(0);
  const [loading, setLoading] = createSignal(false);
  const [error, setError] = createSignal<string | null>(null);
  const [success, setSuccess] = createSignal<OnboardingRequest | null>(null);

  const [formData, setFormData] = createSignal<FormData>({
    tradingName: '',
    contactName: '',
    contactEmail: '',
    contactPhone: '',
    companyAddress: '',
    industry: '',
    companySize: '',
    requestType: '',
    region: '',
    notes: '',
  });

  const steps = ['Company Information', 'Business Details', 'Additional Information'];

  const updateField = (field: keyof FormData, value: string) => {
    setFormData({ ...formData(), [field]: value });
  };

  const validateStep = (step: number): boolean => {
    const data = formData();
    if (step === 0) {
      if (!data.tradingName || !data.contactName || !data.contactEmail) {
        setError('Please fill in all required fields');
        return false;
      }
      if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.contactEmail)) {
        setError('Please enter a valid email address');
        return false;
      }
    }
    setError(null);
    return true;
  };

  const handleNext = () => {
    if (validateStep(activeStep())) {
      setActiveStep(activeStep() + 1);
    }
  };

  const handleBack = () => {
    setActiveStep(activeStep() - 1);
  };

  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    if (!validateStep(activeStep())) return;

    setLoading(true);
    setError(null);

    try {
      const response = await apiClient.post<ApiResponse<OnboardingRequest>>(
        '/api/onboarding',
        formData()
      );

      if (response.data.success) {
        setSuccess(response.data.data);
        setTimeout(() => {
          navigate(`/request/${response.data.data.id}`);
        }, 2000);
      }
    } catch (err: any) {
      setError(err.response?.data?.error || 'Failed to submit request');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Show
      when={!success()}
      fallback={
        <div class="bg-white rounded-lg shadow p-8 text-center">
          <div class="bg-green-50 border border-green-200 text-green-800 px-4 py-3 rounded mb-4">
            Request submitted successfully!
          </div>
          <h2 class="text-2xl font-bold mb-2">
            Reference Number: {success()?.referenceNumber}
          </h2>
          <p class="text-gray-600">Redirecting to request details...</p>
        </div>
      }
    >
      <div class="bg-white rounded-lg shadow p-6">
        <h1 class="text-3xl font-bold mb-6">New Onboarding Request</h1>

        {/* Stepper */}
        <div class="mb-6">
          <div class="flex items-center justify-between mb-4">
            {steps.map((step, index) => (
              <div class="flex items-center flex-1">
                <div
                  class={`flex items-center justify-center w-10 h-10 rounded-full border-2 ${
                    index <= activeStep()
                      ? 'bg-blue-600 border-blue-600 text-white'
                      : 'border-gray-300 text-gray-500'
                  }`}
                >
                  {index + 1}
                </div>
                <span
                  class={`ml-2 text-sm ${
                    index <= activeStep() ? 'text-blue-600 font-medium' : 'text-gray-500'
                  }`}
                >
                  {step}
                </span>
                {index < steps.length - 1 && (
                  <div
                    class={`flex-1 h-0.5 mx-4 ${
                      index < activeStep() ? 'bg-blue-600' : 'bg-gray-300'
                    }`}
                  />
                )}
              </div>
            ))}
          </div>
          <div class="w-full bg-gray-200 rounded-full h-2">
            <div
              class="bg-blue-600 h-2 rounded-full transition-all duration-300"
              style={`width: ${((activeStep() + 1) / steps.length) * 100}%`}
            />
          </div>
        </div>

        <Show when={error()}>
          <div class="bg-red-50 border border-red-200 text-red-800 px-4 py-3 rounded mb-4">
            {error()}
          </div>
        </Show>

        <form onSubmit={handleSubmit}>
          <Show when={activeStep() === 0}>
            <div class="space-y-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  Trading Name <span class="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  required
                  value={formData().tradingName}
                  onInput={(e) => updateField('tradingName', e.currentTarget.value)}
                  class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  Contact Name <span class="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  required
                  value={formData().contactName}
                  onInput={(e) => updateField('contactName', e.currentTarget.value)}
                  class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  Contact Email <span class="text-red-500">*</span>
                </label>
                <input
                  type="email"
                  required
                  value={formData().contactEmail}
                  onInput={(e) => updateField('contactEmail', e.currentTarget.value)}
                  class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  Contact Phone
                </label>
                <input
                  type="tel"
                  value={formData().contactPhone}
                  onInput={(e) => updateField('contactPhone', e.currentTarget.value)}
                  class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  Company Address
                </label>
                <textarea
                  rows={3}
                  value={formData().companyAddress}
                  onInput={(e) => updateField('companyAddress', e.currentTarget.value)}
                  class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
            </div>
          </Show>

          <Show when={activeStep() === 1}>
            <div class="space-y-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  Industry
                </label>
                <select
                  value={formData().industry}
                  onChange={(e) => updateField('industry', e.currentTarget.value)}
                  class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">Select Industry</option>
                  <option value="Manufacturing">Manufacturing</option>
                  <option value="Retail">Retail</option>
                  <option value="Logistics">Logistics</option>
                  <option value="Other">Other</option>
                </select>
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  Company Size
                </label>
                <select
                  value={formData().companySize}
                  onChange={(e) => updateField('companySize', e.currentTarget.value)}
                  class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">Select Size</option>
                  <option value="Small">Small</option>
                  <option value="Medium">Medium</option>
                  <option value="Large">Large</option>
                  <option value="Enterprise">Enterprise</option>
                </select>
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  Request Type
                </label>
                <select
                  value={formData().requestType}
                  onChange={(e) => updateField('requestType', e.currentTarget.value)}
                  class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">Select Type</option>
                  <option value="New Installation">New Installation</option>
                  <option value="Upgrade">Upgrade</option>
                  <option value="Migration">Migration</option>
                </select>
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  Region
                </label>
                <select
                  value={formData().region}
                  onChange={(e) => updateField('region', e.currentTarget.value)}
                  class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">Select Region</option>
                  <option value="North">North</option>
                  <option value="South">South</option>
                  <option value="East">East</option>
                  <option value="West">West</option>
                  <option value="International">International</option>
                </select>
              </div>
            </div>
          </Show>

          <Show when={activeStep() === 2}>
            <div class="space-y-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  Notes
                </label>
                <textarea
                  rows={4}
                  value={formData().notes}
                  onInput={(e) => updateField('notes', e.currentTarget.value)}
                  class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Any additional information..."
                />
              </div>
            </div>
          </Show>

          <div class="flex justify-between mt-6">
            <button
              type="button"
              onClick={handleBack}
              disabled={activeStep() === 0}
              class="px-4 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Back
            </button>
            <Show
              when={activeStep() < steps.length - 1}
              fallback={
                <button
                  type="submit"
                  disabled={loading()}
                  class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {loading() ? 'Submitting...' : 'Submit'}
                </button>
              }
            >
              <button
                type="button"
                onClick={handleNext}
                class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
              >
                Next
              </button>
            </Show>
          </div>
        </form>
      </div>
    </Show>
  );
}
