// frontend-solid/src/components/RequestDetail.tsx
import { createResource, Show, For } from 'solid-js';
import { useParams } from '@solidjs/router';
import apiClient from '../api/client';
import type { OnboardingRequest, ApiResponse } from '../types';

export default function RequestDetail() {
  const params = useParams();

  const fetchRequest = async () => {
    const response = await apiClient.get<ApiResponse<OnboardingRequest>>(
      `/api/onboarding/${params.id}`
    );
    return response.data;
  };

  const [requestData] = createResource(fetchRequest);

  return (
    <Show
      when={requestData()}
      fallback={<div class="text-center py-8">Loading...</div>}
    >
      {(request) => (
        <div class="bg-white rounded-lg shadow p-6">
          <div class="flex justify-between items-start mb-6">
            <div>
              <h1 class="text-3xl font-bold mb-2">
                {request().data.tradingName}
              </h1>
              <p class="text-gray-600">Reference: {request().data.referenceNumber}</p>
            </div>
            <span
              class={`px-3 py-1 rounded-full text-sm font-semibold ${
                request().data.status === 'Completed'
                  ? 'bg-green-100 text-green-800'
                  : request().data.status === 'In Progress'
                  ? 'bg-purple-100 text-purple-800'
                  : request().data.status === 'Under Review'
                  ? 'bg-yellow-100 text-yellow-800'
                  : 'bg-blue-100 text-blue-800'
              }`}
            >
              {request().data.status}
            </span>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h2 class="text-xl font-semibold mb-4">Company Information</h2>
              <dl class="space-y-2">
                <div>
                  <dt class="text-sm font-medium text-gray-500">Trading Name</dt>
                  <dd class="text-sm text-gray-900">{request().data.tradingName}</dd>
                </div>
                <div>
                  <dt class="text-sm font-medium text-gray-500">Industry</dt>
                  <dd class="text-sm text-gray-900">
                    {request().data.industry || 'N/A'}
                  </dd>
                </div>
                <div>
                  <dt class="text-sm font-medium text-gray-500">Company Size</dt>
                  <dd class="text-sm text-gray-900">
                    {request().data.companySize || 'N/A'}
                  </dd>
                </div>
                <div>
                  <dt class="text-sm font-medium text-gray-500">Address</dt>
                  <dd class="text-sm text-gray-900">
                    {request().data.companyAddress || 'N/A'}
                  </dd>
                </div>
              </dl>
            </div>

            <div>
              <h2 class="text-xl font-semibold mb-4">Contact Information</h2>
              <dl class="space-y-2">
                <div>
                  <dt class="text-sm font-medium text-gray-500">Contact Name</dt>
                  <dd class="text-sm text-gray-900">{request().data.contactName}</dd>
                </div>
                <div>
                  <dt class="text-sm font-medium text-gray-500">Email</dt>
                  <dd class="text-sm text-gray-900">{request().data.contactEmail}</dd>
                </div>
                <div>
                  <dt class="text-sm font-medium text-gray-500">Phone</dt>
                  <dd class="text-sm text-gray-900">
                    {request().data.contactPhone || 'N/A'}
                  </dd>
                </div>
              </dl>
            </div>

            <div>
              <h2 class="text-xl font-semibold mb-4">Request Details</h2>
              <dl class="space-y-2">
                <div>
                  <dt class="text-sm font-medium text-gray-500">Request Type</dt>
                  <dd class="text-sm text-gray-900">
                    {request().data.requestType || 'N/A'}
                  </dd>
                </div>
                <div>
                  <dt class="text-sm font-medium text-gray-500">Region</dt>
                  <dd class="text-sm text-gray-900">
                    {request().data.region || 'N/A'}
                  </dd>
                </div>
                <div>
                  <dt class="text-sm font-medium text-gray-500">Assigned Team</dt>
                  <dd class="text-sm text-gray-900">
                    {request().data.assignedTeam || 'Unassigned'}
                  </dd>
                </div>
                <div>
                  <dt class="text-sm font-medium text-gray-500">Progress</dt>
                  <dd class="text-sm text-gray-900">
                    <div class="w-full bg-gray-200 rounded-full h-2 mt-1">
                      <div
                        class="bg-blue-600 h-2 rounded-full"
                        style={`width: ${request().data.completionPercentage}%`}
                      />
                    </div>
                    {request().data.completionPercentage}%
                  </dd>
                </div>
              </dl>
            </div>

            <div>
              <h2 class="text-xl font-semibold mb-4">Timeline</h2>
              <dl class="space-y-2">
                <div>
                  <dt class="text-sm font-medium text-gray-500">Created</dt>
                  <dd class="text-sm text-gray-900">
                    {new Date(request().data.createdAt).toLocaleString()}
                  </dd>
                </div>
                <div>
                  <dt class="text-sm font-medium text-gray-500">Last Updated</dt>
                  <dd class="text-sm text-gray-900">
                    {new Date(request().data.updatedAt).toLocaleString()}
                  </dd>
                </div>
              </dl>
            </div>
          </div>

          {request().data.notes && (
            <div class="mt-6">
              <h2 class="text-xl font-semibold mb-2">Notes</h2>
              <p class="text-gray-700 bg-gray-50 p-4 rounded">
                {request().data.notes}
              </p>
            </div>
          )}

          {request().data.statusHistory && request().data.statusHistory.length > 0 && (
            <div class="mt-6">
              <h2 class="text-xl font-semibold mb-4">Status History</h2>
              <div class="space-y-2">
                <For each={request().data.statusHistory}>
                  {(history) => (
                    <div class="border-l-4 border-blue-500 pl-4 py-2">
                      <p class="text-sm font-medium">
                        {history.oldStatus || 'New'} → {history.newStatus}
                      </p>
                      <p class="text-xs text-gray-500">
                        {new Date(history.changedAt).toLocaleString()}
                      </p>
                      {history.notes && (
                        <p class="text-sm text-gray-600 mt-1">{history.notes}</p>
                      )}
                    </div>
                  )}
                </For>
              </div>
            </div>
          )}
        </div>
      )}
    </Show>
  );
}

// frontend/src/components/RequestDetail.tsx
import React from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import {
  Box,
  Paper,
  Typography,
  Button,
  Chip,
  LinearProgress,
  Grid,
  Divider,
  Alert,
} from '@mui/material';
import apiClient from '../api/client';
import { OnboardingRequest, ApiResponse } from '../types';

const RequestDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();

  const { data, isLoading, error } = useQuery<ApiResponse<OnboardingRequest>>({
    queryKey: ['onboarding', id],
    queryFn: async () => {
      const response = await apiClient.get(`/onboarding/${id}`);
      return response.data;
    },
    enabled: !!id,
  });

  const request = data?.data;

  const getStatusColor = (status: string) => {
    const colors: Record<string, 'default' | 'primary' | 'secondary' | 'error' | 'info' | 'success' | 'warning'> = {
      'New': 'info',
      'Under Review': 'warning',
      'In Progress': 'primary',
      'Completed': 'success',
      'On Hold': 'error',
    };
    return colors[status] || 'default';
  };

  if (isLoading) {
    return <LinearProgress />;
  }

  if (error || !request) {
    return (
      <Alert severity="error">
        Failed to load request details
      </Alert>
    );
  }

  return (
    <Box>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 2 }}>
        <Typography variant="h4">
          Request Details
        </Typography>
        <Button variant="outlined" onClick={() => navigate('/dashboard')}>
          Back to Dashboard
        </Button>
      </Box>

      <Paper sx={{ p: 3 }}>
        <Grid container spacing={3}>
          <Grid item xs={12}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
              <Typography variant="h5">
                {request.tradingName}
              </Typography>
              <Chip
                label={request.status}
                color={getStatusColor(request.status)}
              />
            </Box>
            <Typography variant="body2" color="text.secondary">
              Reference: {request.referenceNumber}
            </Typography>
          </Grid>

          <Grid item xs={12}>
            <Divider />
          </Grid>

          <Grid item xs={12} md={6}>
            <Typography variant="subtitle2" color="text.secondary" gutterBottom>
              Contact Information
            </Typography>
            <Typography variant="body1"><strong>Name:</strong> {request.contactName}</Typography>
            <Typography variant="body1"><strong>Email:</strong> {request.contactEmail}</Typography>
            {request.contactPhone && (
              <Typography variant="body1"><strong>Phone:</strong> {request.contactPhone}</Typography>
            )}
          </Grid>

          <Grid item xs={12} md={6}>
            <Typography variant="subtitle2" color="text.secondary" gutterBottom>
              Business Details
            </Typography>
            {request.industry && (
              <Typography variant="body1"><strong>Industry:</strong> {request.industry}</Typography>
            )}
            {request.companySize && (
              <Typography variant="body1"><strong>Company Size:</strong> {request.companySize}</Typography>
            )}
            {request.requestType && (
              <Typography variant="body1"><strong>Request Type:</strong> {request.requestType}</Typography>
            )}
            {request.region && (
              <Typography variant="body1"><strong>Region:</strong> {request.region}</Typography>
            )}
          </Grid>

          <Grid item xs={12}>
            <Divider />
          </Grid>

          <Grid item xs={12} md={6}>
            <Typography variant="subtitle2" color="text.secondary" gutterBottom>
              Assignment
            </Typography>
            <Typography variant="body1">
              <strong>Team:</strong> {request.assignedTeam || 'Unassigned'}
            </Typography>
            <Box sx={{ mt: 2 }}>
              <Typography variant="body2" color="text.secondary" gutterBottom>
                Progress: {request.completionPercentage}%
              </Typography>
              <LinearProgress
                variant="determinate"
                value={request.completionPercentage}
                sx={{ height: 8, borderRadius: 4 }}
              />
            </Box>
          </Grid>

          <Grid item xs={12} md={6}>
            <Typography variant="subtitle2" color="text.secondary" gutterBottom>
              Timeline
            </Typography>
            <Typography variant="body1">
              <strong>Created:</strong> {new Date(request.createdAt).toLocaleString()}
            </Typography>
            <Typography variant="body1">
              <strong>Updated:</strong> {new Date(request.updatedAt).toLocaleString()}
            </Typography>
          </Grid>

          {request.companyAddress && (
            <Grid item xs={12}>
              <Typography variant="subtitle2" color="text.secondary" gutterBottom>
                Company Address
              </Typography>
              <Typography variant="body1">{request.companyAddress}</Typography>
            </Grid>
          )}

          {request.notes && (
            <Grid item xs={12}>
              <Divider sx={{ my: 2 }} />
              <Typography variant="subtitle2" color="text.secondary" gutterBottom>
                Notes
              </Typography>
              <Typography variant="body1">{request.notes}</Typography>
            </Grid>
          )}

          {request.statusHistory && request.statusHistory.length > 0 && (
            <Grid item xs={12}>
              <Divider sx={{ my: 2 }} />
              <Typography variant="subtitle2" color="text.secondary" gutterBottom>
                Status History
              </Typography>
              {request.statusHistory.map((history) => (
                <Box key={history.id} sx={{ mb: 1 }}>
                  <Typography variant="body2">
                    {history.oldStatus || 'N/A'} → {history.newStatus || 'N/A'}
                  </Typography>
                  <Typography variant="caption" color="text.secondary">
                    {new Date(history.changedAt).toLocaleString()} by {history.changedBy || 'System'}
                  </Typography>
                </Box>
              ))}
            </Grid>
          )}
        </Grid>
      </Paper>
    </Box>
  );
};

export default RequestDetail;
