// frontend-solid/src/App.tsx
import { lazy } from 'solid-js';
import { Route, Routes } from '@solidjs/router';
import Layout from './components/Layout';
import Dashboard from './components/Dashboard';

// Lazy load routes for code splitting
const OnboardingForm = lazy(() => import('./components/OnboardingForm'));
const RequestDetail = lazy(() => import('./components/RequestDetail'));

export default function App() {
  return (
    <Layout>
      <Routes>
        <Route path="/" component={Dashboard} />
        <Route path="/new" component={OnboardingForm} />
        <Route path="/request/:id" component={RequestDetail} />
      </Routes>
    </Layout>
  );
}

// frontend/src/App.tsx
import React from 'react';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ThemeProvider, createTheme, CssBaseline } from '@mui/material';
import OnboardingForm from './components/OnboardingForm';
import Dashboard from './components/Dashboard';
import RequestDetail from './components/RequestDetail';
import Layout from './components/Layout';

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      retry: 1,
    },
  },
});

const theme = createTheme({
  palette: {
    primary: {
      main: '#1976d2',
    },
    secondary: {
      main: '#dc004e',
    },
  },
});

function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <BrowserRouter>
          <Layout>
            <Routes>
              <Route path="/" element={<OnboardingForm />} />
              <Route path="/dashboard" element={<Dashboard />} />
              <Route path="/request/:id" element={<RequestDetail />} />
            </Routes>
          </Layout>
        </BrowserRouter>
      </ThemeProvider>
    </QueryClientProvider>
  );
}

export default App;
